function data_out = choice_ev_trial(choice_info)

rwd_selectBigEV = choice_info.option1_rwd_ev > choice_info.option2_rwd_ev & ...
    choice_info.option_selected == 0 |...
choice_info.option1_rwd_ev < choice_info.option2_rwd_ev & ...
    choice_info.option_selected == 1;

punish_selectBigEV = choice_info.option1_punish_ev > choice_info.option2_punish_ev & ...
    choice_info.option_selected == 0 |...
choice_info.option1_punish_ev < choice_info.option2_punish_ev & ...
    choice_info.option_selected == 1;

diff_selectPosVal =(choice_info.option1_rwd_ev - choice_info.option1_punish_ev) >...
    (choice_info.option2_rwd_ev - choice_info.option2_punish_ev) & ...    % Option 1 is more positively valenced
        choice_info.option_selected == 0 | ...
(choice_info.option1_rwd_ev - choice_info.option1_punish_ev) <...
    (choice_info.option2_rwd_ev - choice_info.option2_punish_ev) & ...    % Option 2 is more positively valenced
        choice_info.option_selected == 1;    
    
data_out.rwd_selectBigEV = rwd_selectBigEV;
data_out.punish_selectBigEV = punish_selectBigEV;
data_out.diff_selectPosVal = diff_selectPosVal;

end